import 'dotenv/config'

const {
  PORT,
  GITHUB_CLIENT,
  GITHUB_SECRET,
  GOOGLE_CLIENT,
  GOOGLE_SECRET,
  GOOGLE_CALLBACK,
  DEPLOYED_CLIENT,
  LOCAL_CLIENT,
  JWT_SECRET,
  SUPABASE_PROJECT_URL,
  SUPABASE_KEY,
  POSTGRES_USER = 'admin',
  POSTGRES_PASSWORD,
  ENVIRONMENT = 'DEVELOPMENT'
} = process.env

export {
  PORT,
  GITHUB_CLIENT,
  GITHUB_SECRET,
  GOOGLE_CLIENT,
  GOOGLE_SECRET,
  GOOGLE_CALLBACK,
  DEPLOYED_CLIENT,
  LOCAL_CLIENT,
  JWT_SECRET,
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  SUPABASE_PROJECT_URL,
  SUPABASE_KEY,
  ENVIRONMENT
}
